services:
  - type: web
    name: cooking-oil-ml-demo
    runtime: docker
    plan: free
    rootDir: ml_app
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
